### PR TITLE
Fix HTML validation, character entities, and typos

### PR DESCRIPTION
**Pull request by mitchellevan**
Fix HTML validation: matching opening and closing tags.
Fix character entities: em dashes and quotation marks.
Fix minor typos.

### CODE REVIEW

**Comment by ZoeBijl** [comment]
Before I accept this, why are all quotes turned into dumb-quotes? It's a UTF-8 document, should do smart quotes, dashes, etc just fine. The messed up end tags are the only thing that the [nu validator](https://validator.w3.org/nu/) throws at me.

**Comment by StommePoes** [comment]
I personally like "dumb" quotes, when I do smart quotes I do them as HTML entities: 8220 and 8221 respectively. Smart quotes have traditionally been the harbinger of Zalgo and Windows-users destroying whole docs.

That said, my system didn't have any issues with the "smart" quotes, they were displayed in the only way my fonts can: as dumb (and not into weird nasty smart-quote stuff), so they must've been ok. Searching for something I can't physically type is a pain, though.

I also approve of the mdash/8212, but like above, that's a personal preference.

Or Michiel, this being open-sores, we could just out-vote you : P

Though it honestly doesn't matter to me since my system didn't complain about the quotes. Count me neutral.

**Comment by ZoeBijl** [comment]
It was more a question than criticisms.

**Comment by ZoeBijl** [comment]
I've added pretty quotes via CSS now, muwhahaha: https://github.com/MichielBijl/font-awesome/commit/f70c25b0677502556cf177706ffce560227ee470

**Pull request merged**
